### ISSUE TITLE
Could not pass event PlayerInteractEvent to FactoryMod v1.1               

### ISSUE THREAD

**Issue by ttk2** [ttk2/FactoryMod#60]
2014-07-14 13:55:00 [ERROR] Could not pass event PlayerInteractEvent to FactoryMod v1.1                                                                                 │·······
org.bukkit.event.EventException                                                                                                                                         │·······
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                │·······
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                  │·······
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                        │·······
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                │·······
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                │·······
        at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]   │·······
        at net.minecraft.server.v1_7_R1.PlayerInteractManager.dig(PlayerInteractManager.java:103) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                       │·······
        at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:548) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                   │·······
        at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                           │·······
        at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                       │·······
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                       │·······
        at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                    │·······
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                     │·······
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                     │·······
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                     │·······
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                   │·······
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                     │·······
Caused by: java.lang.NullPointerException

**Comment by pruby** [comment]
Hi ttk,

Is there another stack trace after that last line? That's the one we need more.

**Comment by ttk2** [comment]
2014-07-14 14:08:55 [ERROR] Could not pass event PlayerInteractEvent to FactoryMod v1.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PlayerInteractManager.dig(PlayerInteractManager.java:103) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:548) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
Caused by: java.lang.NullPointerException
2014-07-14 14:08:55 [ERROR] [Citadel] 
2014-07-14 14:08:55 [ERROR] [Citadel] Internal error!
2014-07-14 14:08:55 [ERROR] [Citadel] Include the following into your bug report:
2014-07-14 14:08:55 [ERROR] [Citadel]           ======= SNIP HERE =======
2014-07-14 14:08:55 [ERROR] [Citadel] java.lang.NullPointerException
2014-07-14 14:08:55 [ERROR] [Citadel]           ======= SNIP HERE =======
2014-07-14 14:08:55 [ERROR] [Citadel]
